### ISSUE TITLE
Empty input file error

### ISSUE THREAD

**Issue by vkyprmr** [ErasmusMC-NeuroOnco/DeepDicomSort#22]
Hi, I am using DeepDicomSort to sort some Dicom files. In my first use, it ran smoothly and did a great job. Since, then I am trying to use it and it is throwing the following error message:
```
Sorting DICOM to structured folders....
Checking and splitting for double scans in folders....
Converting DICOMs to NIFTI....
Moving RGB valued images.....
Extracting single point from 4D images....
Reorient to standard space....
Resampling images....
Extracting slices from images...
Rescaling image intensity....
Creating label file....
0.04404878616333008
/DeepDicomSort/Preprocessing/NIFTI_preparation_functions.py:202: UserWarning: genfromtxt: Empty input file: "/input/DATA/Scans_4D.txt"
  images_4D = np.genfromtxt(images_4D_file, dtype='str')
predict_from_CNN.py:24: UserWarning: genfromtxt: Empty input file: "/input/DATA/labels.txt"
  labels = np.genfromtxt(label_file, dtype='str')
Traceback (most recent call last):
  File "predict_from_CNN.py", line 39, in <module>
    test_image_IDs, test_image_labels, _, extra_inputs = load_labels(test_label_file)
  File "predict_from_CNN.py", line 25, in load_labels
    label_IDs = labels[:, 0]
IndexError: too many indices for array
Traceback (most recent call last):
  File "Rename_folders_from_predictions.py", line 25, in <module>
    predictions = np.loadtxt(prediction_file, dtype=np.str)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
OSError: /output/Predictions_model_all_brain_tumor_data.csv not found.
Traceback (most recent call last):
  File "Sort_to_BIDS.py", line 28, in <module>
    predictions = np.loadtxt(prediction_file, dtype=np.str)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
OSError: /output/Predictions_model_all_brain_tumor_data.csv not found.
```

I tried running it on the same images, and even then it is throwing the same error. Can you please help me out?

**Comment by Svdvoort** [comment]
It seems like it can't find the folder, or there are no images inside the subfolder.

Are you running the docker or are your running the code from a local install? 

Are you sure the folder `/input/DATA/` exists and is writable? 

Are there indeed DICOM/NIFTI images in `/input/DATA/`?

**Comment by vkyprmr** [comment]
Sorry. You were right. After fixing the path and permissions, it worked.
